version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "127.0.0.1:6379:6379"  # Restrict Redis to local access
    volumes:
      - redis-data:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass "sqq24"  # Add password authentication
    networks:
      - redis
volumes:
  redis-data: {}
networks:
  redis:
    driver: bridge
